# Generated by Django 4.1.2 on 2023-03-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('priority', models.TextField(max_length=100)),
                ('materials', models.TextField(max_length=100)),
            ],
        ),
    ]
