# Generated by Django 4.1.2 on 2023-03-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_department_remove_task_depart_alter_task_name_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
