# Generated by Django 4.1.2 on 2023-03-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_course_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priority',
            new_name='Purpose',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='purpose',
        ),
    ]
