# Generated by Django 4.1.2 on 2023-03-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_rename_priority_purpose_rename_priority_task_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
