# Generated by Django 4.1.2 on 2023-03-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_purpose_alter_task_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='purpose',
        ),
    ]
