# Generated by Django 4.1.2 on 2023-03-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_remove_task_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
