# Generated by Django 4.1.2 on 2023-03-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_purpose_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
